[theme]
base = "light"
primaryColor = "#C8102E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F2EF"
textColor = "#2B2B2B"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
